# Generated by Django 5.2.7 on 2025-11-23 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('issued', models.DateField()),
                ('country', models.CharField()),
                ('image', models.CharField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
