# Generated by Django 5.2.7 on 2025-11-25 15:19

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_film_country_alter_film_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(unique=True)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 11, 25, 17, 19, 6, 112455))),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.film')),
            ],
        ),
    ]
