# Generated by Django 5.2.7 on 2025-11-25 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_film_id_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 17, 29, 8, 602682)),
        ),
    ]
