# Generated by Django 5.2.7 on 2025-11-25 15:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 17, 30, 44, 254858)),
        ),
        migrations.AddField(
            model_name='film',
            name='ganre',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.ganre'),
            preserve_default=False,
        ),
    ]
