# Generated by Django 5.2.7 on 2025-11-25 16:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ganre_alter_comment_date_film_ganre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 18, 10, 40, 513403)),
        ),
        migrations.AlterField(
            model_name='film',
            name='ganre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ganre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
