# Generated by Django 5.2.7 on 2025-11-25 16:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_date_alter_film_ganre_alter_film_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 18, 12, 53, 898792)),
        ),
        migrations.AlterField(
            model_name='film',
            name='ganre',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.ganre'),
            preserve_default=False,
        ),
    ]
