# Generated by Django 5.2.7 on 2025-11-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_comment_date_alter_film_ganre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 18, 57, 25, 801927)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(),
        ),
    ]
