# Generated by Django 5.2.7 on 2025-11-30 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_date_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('test', 'test')]},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 14, 9, 40, 446306)),
        ),
    ]
