# Generated by Django 5.2.7 on 2025-11-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_comment_options_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 16, 1, 38, 261498)),
        ),
    ]
