# Generated by Django 5.2.7 on 2025-11-30 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 5, 23, 495178)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 5, 23, 495066)),
        ),
    ]
