# Generated by Django 5.2.7 on 2025-11-30 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_issued_alter_discussion_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 5, 57, 73545)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 5, 57, 73429)),
        ),
    ]
