# Generated by Django 5.2.7 on 2025-11-30 23:16

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_issued_alter_discussion_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 15, 49, 847915)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 15, 49, 847797)),
        ),
    ]
