# Generated by Django 5.2.7 on 2025-11-30 23:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_discussion_subject_alter_comment_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.category'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 30, 23, 41, 21, 209374)),
        ),
    ]
