# Generated by Django 5.2.7 on 2025-12-01 01:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_comment_likes_remove_discussion_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.discussion'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 1, 1, 25, 50, 130171)),
        ),
    ]
